spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        lob:
          non-contextual-creation: true